### ISSUE TITLE
Search directories with ranger/fzf

### ISSUE THREAD

**Issue by j-degreef** [gotbletu/shownotes#11]
Hi,

On your page about integration of fzf and ranger, in the fzf_select command you wrote "With a prefix argument select only directories." Can you clarify on what should be and how to enter this prefix ?

Thanks in advance,
Jérôme

**Comment by gotbletu** [comment]
seems thats just the comment/description of what the code does, that the author wrote.

**Comment by j-degreef** [comment]
I've found the answer :)
The prefix is what is called a quantifier.
From the Ranger man page :

> map key command
>          Assign the key combination to the given command.  Whenever you type
>          the key/keys, the command will be executed.  Additionally, if you use
>          a quantifier when typing the key, like 5j, it will be passed to the
>          command as the attribute "self.quantifier".

In our case the quantifier is any key before pressing the fzf_select keybinding.
[https://github.com/gotbletu/shownotes/blob/master/ranger_file_locate_fzf.md)]

**Comment by gotbletu** [comment]
oh thats some deep research, i only just copy paste lols

**Comment by j-degreef** [comment]
Well, just a research to understand how to make it work ;)
Maybe you can add this information to the relevant page, that will make people stop scratching their head as I did a few days ago :)

**Comment by gotbletu** [comment]
sure i can update that
