### ISSUE TITLE
rofi-locate: don't run xdg-open if escaped

### ISSUE THREAD

**Issue by smilingverb** [gotbletu/shownotes#16]
I'd propose to use xargs -r -0 to cancel the operation if no file is selected:

locate home media | rofi -threads 0 -width 100 -dmenu -i -p "locate:" | xargs -r -0 xdg-open

**Comment by gotbletu** [comment]
i digg it thanks, updated now
https://github.com/gotbletu/shownotes/blob/master/rofi_locate.md
