### ISSUE TITLE
ranger does not support fzf

### ISSUE THREAD

**Issue by fabOnReact** [gotbletu/shownotes#22]
I run in the current issue

ranger version: 1.8.1, executed with python 2.7.15rc1
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 94, in main
    load_settings(fm, arg.clean)
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 272, in load_settings
    import commands
  File "/home/fabrizio/.config/ranger/commands.py", line 3, in <module>
    class fzf_select(Command):
NameError: name 'Command' is not defined

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues

a maybe [relevant issue](https://github.com/gotbletu/shownotes/issues/11)

**Comment by rcrx** [comment]
Same here.

**Comment by cuppajoeman** [comment]
I also have this issue

**Comment by gotbletu** [comment]
im on ranger 1.9.2 so can't really go back to try those; Try starting over with a fresh ranger config file

**Comment by gotbletu** [comment]
they updated their code a little bit also maybe that will help you guys? https://github.com/ranger/ranger/wiki/Custom-Commands

**Comment by fabOnReact** [comment]
@gotbletu I am also running ranger 1.9.2 unluckily. It works for me now. Thanks 
![image](https://user-images.githubusercontent.com/24992535/57573329-524f0380-7426-11e9-9c6e-807f97ca63fc.png)

**Comment by cuppajoeman** [comment]
I just copied the code for the commands.py file from your  shownotes, but it doesn't have this import statement.

`from ranger.api.commands import Command`

So I just had to add this to the top of the file and it's working now.

**Comment by gotbletu** [comment]
@fabriziobertoglio1987 Good to hear, kicking ass now =)

@cuppajoeman that weird, that import code should of been on there by default when you generate a fresh config file; anyways this should count as solved now i hope 2/3 majority
