### ISSUE TITLE
pulseaudio-dynamic-range-compression.md

### ISSUE THREAD

**Issue by atomGit** [gotbletu/shownotes#31]
i believe neither pavucontrol nor ncpamixer is required for KDE/Plasma - at least certainly not in my case - everything can be controlled/switched from the normal volume applet in the tray

thanks for this guide btw - been using it a long time and i appreciate the compressor effect a lot

**Comment by gotbletu** [comment]
hehe im surprise no other distro has this option built-in, is a must for me atleast =)

Yes, well is not require to install but i had to put something easy for folks to change audio stream if they want to
