### ISSUE TITLE
License terms

### ISSUE THREAD

**Issue by cybardev** [gotbletu/shownotes#34]
Hey there. I came across a script of yours (any_term_dropdown.sh) that I would like to add to one of my repos and change the code to add/remove features (I'd be sure to credit you). Is this permitted? As far as I can understand, if you do not include a LICENSE (md/txt), standard copyright laws apply and I'm not free to modify your code legally.

So what I'm asking is that if it was intentional, could you please clearly indicate in your readme that the scripts are copyrighted? I see that you have the same script in your dotfiles_v2 repo but even that repo lacks a FOSS license, making it copyrighted. Indicating copyright in the readme is not obligatory but does help avoid confusion.

Else, if you intend people to freely use, modify and redistribute your work, may I suggest that you please use a suitable license like the GPL_v3 (the standard FOSS) or MIT (if you're feeling really generous).

Thank you.
Great content, great scripts. Cheers.

**Comment by gotbletu** [comment]
oh i never consider that since all my scripts are so basic lols; but yea for sure you can use it, hope you make it better then i can =), i dont care about license but since you want to make this proper, ill put it under GPLv3 just to stick to the FOSS side

**Comment by cybardev** [comment]
> I'll put it under GPLv3 just to stick to the FOSS side

Great. Thanks a lot. Do add the license soon please if youcan (I'm itching to get started). Making a new file on Github named LICENSE.md shows GPL3 template so that shouldn't be too cumbersome.

I will close the issue once the LICENSE.md has been updated.
Thanks for the awesome scripts 😊

**Comment by gotbletu** [comment]
alright here it is https://github.com/gotbletu/shownotes/blob/master/LICENSE.txt

**Comment by cybardev** [comment]
Marvellous.
Thanks again.
Good day to you, sire. 😁
