### ISSUE TITLE
Command line youtube fuzzy finder.

### ISSUE THREAD

**Issue by pystardust** [gotbletu/shownotes#35]
After seeing you last video on fzf-nova, 
I thought you might like one of my scripts for browsing and playing youtube videos from the command line.
It is just a small shell script the scrapes youtube parses its json and gives a formatted output.
I have added features like downloading, music, autoplay format selector.
Hope you like it
https://github.com/pystardust/ytfzf

**Comment by gotbletu** [comment]
thanks ill give a look

**Comment by pystardust** [comment]
I have added dmenu and rofi today. I would be happy to take suggestions and PRs.

**Comment by gotbletu** [comment]
well maybe add **task-spooler** support then u can select multiple videos with TAB in fzf so i dont have to wait for one video to end to select another

**Comment by pystardust** [comment]
Thats an interesting Idea, Ill look into it tomorrow . 
@gotbletu  I added image support.

**Comment by pystardust** [comment]
> well maybe add **task-spooler** support then u can select multiple videos with TAB in fzf so i dont have to wait for one video to end to select another

I have added the feature as requested

**Comment by gotbletu** [comment]
very cool, awesome update thanks

**Comment by pystardust** [comment]
Thanks for making a video on it!
I didn't use tsp cause you cannot go to the previous track once you close the player.  And it would get harder clear the que when there are multiple videos playing.

**Comment by gotbletu** [comment]
no probs, i understand it from your point of view, not everyone uses tsp or understands what it is; tsp is mainly for my subscribers that I've explained in the past =) ; since they use it on newsboat, w3m, and now ytfzf, all in the same queue system.
