### ISSUE TITLE
name 'os' is not defined when pressing enter

### ISSUE THREAD

**Issue by Pllet** [gotbletu/shownotes#36]
Hi, i just installed fzf in ranger following the tutorial. press ctrl+f, fzf opens, search a file and when press enter, it closes returning to ranger showing: "name 'os' is not defined".

**Comment by gotbletu** [comment]
theres an updated code for **fzf integration** on their site

https://github.com/ranger/ranger/wiki/Custom-Commands

**Comment by Pllet** [comment]
Hi, tried the config, but the same issue is still happening.
![image](https://user-images.githubusercontent.com/13187646/110343359-2a715c80-800b-11eb-8581-65f0003e0956.png)

This is the config i am using

`
from ranger.api.commands import Command

class fzf_select(Command):
    """
    :fzf_select
    Find a file using fzf.
    With a prefix argument to select only directories.

    See: https://github.com/junegunn/fzf
    """

    def execute(self):
        import subprocess
        from ranger.ext.get_executables import get_executables

        if 'fzf' not in get_executables():
            self.fm.notify('Could not find fzf in the PATH.', bad=True)
            return

        fd = None
        if 'fdfind' in get_executables():
            fd = 'fdfind'
        elif 'fd' in get_executables():
            fd = 'fd'

        if fd is not None:
            hidden = ('--hidden' if self.fm.settings.show_hidden else '')
            exclude = "--no-ignore-vcs --exclude '.git' --exclude '*.py[co]' --exclude '__pycache__'"
            only_directories = ('--type directory' if self.quantifier else '')
            fzf_default_command = '{} --follow {} {} {} --color=always'.format(
                fd, hidden, exclude, only_directories
            )
        else:
            hidden = ('-false' if self.fm.settings.show_hidden else r"-path '*/\.*' -prune")
            exclude = r"\( -name '\.git' -o -iname '\.*py[co]' -o -fstype 'dev' -o -fstype 'proc' \) -prune"
            only_directories = ('-type d' if self.quantifier else '')
            fzf_default_command = 'find -L . -mindepth 1 {} -o {} -o {} -print | cut -b3-'.format(
                hidden, exclude, only_directories
            )

        env = os.environ.copy()
        env['FZF_DEFAULT_COMMAND'] = fzf_default_command
        env['FZF_DEFAULT_OPTS'] = '--height=40% --layout=reverse --ansi --preview="{}"'.format('''
            (
                batcat --color=always {} ||
                bat --color=always {} ||
                cat {} ||
                tree -ahpCL 3 -I '.git' -I '*.py[co]' -I '__pycache__' {}
            ) 2>/dev/null | head -n 100
        ''')

        fzf = self.fm.execute_command('fzf --no-multi', env=env,
                                      universal_newlines=True, stdout=subprocess.PIPE)
        stdout, _ = fzf.communicate()
        if fzf.returncode == 0:
            selected = os.path.abspath(stdout.strip())
            if os.path.isdir(selected):
                self.fm.cd(selected)
            else:
                self.fm.select_file(selected)


`

**Comment by gotbletu** [comment]
not sure then, hope you are using the latest ranger/python versions; else try asking them about it

**Comment by Pllet** [comment]
It worked!
i used this command to create the config file ranger --copy-config=commands, the created file does an import of 'os', and updated the python version.
Thank you!
