### ISSUE TITLE
game2m3u - backwards?

### ISSUE THREAD

**Issue by chewvodka** [gotbletu/shownotes#38]
I just ran through some game tests.. looks like all my generated m3u files have the disk order backwards:

Final Fantasy VII (USA) (Disc 3).cue
Final Fantasy VII (USA) (Disc 2).cue
Final Fantasy VII (USA) (Disc 1).cue

**Comment by gotbletu** [comment]
Thanks, good catch, i added sort now, should fix it

https://github.com/gotbletu/shownotes/blob/master/game2m3u
