### ISSUE TITLE
fzf-nova some minor corrections

### ISSUE THREAD

**Issue by RaZ0rr-Two** [gotbletu/shownotes#42]
For alacritty, I had to change the commands to

```
alacritty -t fzf-nova --option window.dimensions.columns=90 --option window.dimensions.lines=20 -option window.position.x=350 -option window.position.y=200 -e path/to/fzf-nova
```
Change dimensions and position accordingly. Also, you can provide `--config-file` to give a path to custom .yml file (from `man alacritty`)

Also, I added `-L` to `find` command before the path since I have fzf-nova as a symlink fro my dotfiles repo.

**Comment by RaZ0rr-Two** [comment]
Also, how can I go back after I select an option. Like after selecting `applauncher` . How to cancel and go back to home

**Comment by gotbletu** [comment]
1. might be they updated the alacritty version from when i last used. Thanks for the info tho
2. there is no option to go back after you selected a script, just hit escape and launch it again is the quickest way
