### ISSUE TITLE
Completely Broken on Debian Sid w/ Terminator?

### ISSUE THREAD

**Issue by Xemptuous** [gotbletu/shownotes#53]
I got this recently hoping to try it out, but I was completely unable to get it working.

I'm using Debian bookworm/sid, terminator CLI, and w3m 0.5.3.

When installing with `npm install -g readability-cli`, I get images rendering in w3m behind my terminal, popping to the foreground on movement. When using the given `\r` command, I am presented by a flash of css styling, followed by an empty buffer.

Am I doing something wrong here, or is this broken with my current setup?

**Comment by gotbletu** [comment]
w3m image display is not perfect, some terminal handles it better then others; im using xterm if u want to try that instead

**Comment by Xemptuous** [comment]
I ended up removing w3m-image for the npm version to work properly, but still ran into issues with readability. I switched to the python version and it works without any issues, even with w3m-image,  so I will be sticking with that version.
