### ISSUE TITLE
ffmpeg_x11grab_screencast

### ISSUE THREAD

**Issue by marteaurouge** [gotbletu/shownotes#6]
Hey Gotbletu,

are you still using the setup from ffmpeg_x11grab_screencast.txt to do your podcasts?

Good job btw, your videos are really interesting!

**Comment by gotbletu** [comment]
yea still using ffmpeg to record =)

**Comment by marteaurouge** [comment]
I'll give it a try, thanks! 

I don't understand why we have to recompile ffmpeg btw, isn't it a standard tool in most video projects? Maybe is it related to some licensing issues, so they can't add it the depots?

Btw is it possible to have the name of the software displaying the key you press in your podcasts?

**Comment by gotbletu** [comment]
On some distrubutions they dont have mp3, h264 codec installed because of licensing.
Screenkey for displaying key presses.
