### ISSUE TITLE
TuxTV Close 

### ISSUE THREAD

**Issue by kirkins** [gotbletu/shownotes#9]
With the TuxTv script. If you close using 'q' everything stops but if you close the terminal menu and leave vlc playing then later close vlc the sound will keep playing even though the window is closed.

I've just been opening the menu in tmux and re-opening when I want to change channels or close. 

Do you know how I can manually close a backgrounded vlc steam if that happens?

**Comment by gotbletu** [comment]
Well usually i would just leave the tmux session for it open but if you want it killall vlc instances, you can use this command

```
killall -9 vlc
```

 or bust out **htop** and kill it that way if you like also:

```
start htop
hit \
type vlc
hit enter
hit k
hit 9
hit enter
```

**Comment by kirkins** [comment]
perfect, thx
